# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Volra < Formula
  desc "Deploy and monitor AI agents on your own servers"
  homepage "https://github.com/romerox3/volra"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romerox3/volra/releases/download/v1.0.3/volra-1.0.3-darwin-amd64.tar.gz"
      sha256 "5de81234c01ca1364734de78c99b9d7ee99ed5b4d476262379983784e9f24f44"

      define_method(:install) do
        bin.install "volra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romerox3/volra/releases/download/v1.0.3/volra-1.0.3-darwin-arm64.tar.gz"
      sha256 "7fcbb512e2bae1c2c947b8a3aea2367573ecd5d150d50dd50969f688876032cc"

      define_method(:install) do
        bin.install "volra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/romerox3/volra/releases/download/v1.0.3/volra-1.0.3-linux-amd64.tar.gz"
      sha256 "bba5610f1bce1c1abde75aded0775b277db6f3decd074c7ddecd974f5c96d15a"
      define_method(:install) do
        bin.install "volra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/romerox3/volra/releases/download/v1.0.3/volra-1.0.3-linux-arm64.tar.gz"
      sha256 "bdc408a8ae9158158477277c24abf5fd7d1670ac4f7f90ee610981fe8fb7080c"
      define_method(:install) do
        bin.install "volra"
      end
    end
  end

  test do
    system "#{bin}/volra", "--version"
  end
end
