# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Volra < Formula
  desc "Deploy and monitor AI agents on your own servers"
  homepage "https://github.com/romerox3/volra"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romerox3/volra/releases/download/v1.0.5/volra-1.0.5-darwin-amd64.tar.gz"
      sha256 "3a005ea3345db5250ef975bd53af2798b58fcad0b4f27f3849187c92c5c5c47d"

      define_method(:install) do
        bin.install "volra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romerox3/volra/releases/download/v1.0.5/volra-1.0.5-darwin-arm64.tar.gz"
      sha256 "3cded1b5a80c11955459c163fbdc6dcc3d99692ab0aa06f5cf3b0eb3a06b525f"

      define_method(:install) do
        bin.install "volra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/romerox3/volra/releases/download/v1.0.5/volra-1.0.5-linux-amd64.tar.gz"
      sha256 "499a4cbb65e60a631f39f7b9f092b87772564e37a1bd589f2d1430b0ea89a340"
      define_method(:install) do
        bin.install "volra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/romerox3/volra/releases/download/v1.0.5/volra-1.0.5-linux-arm64.tar.gz"
      sha256 "0ed194e6010b4864c69989e354a13b85c585bbdea7f6fdb1220e1ada9836de5b"
      define_method(:install) do
        bin.install "volra"
      end
    end
  end

  test do
    system "#{bin}/volra", "--version"
  end
end
