# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Volra < Formula
  desc "Deploy and monitor AI agents on your own servers"
  homepage "https://github.com/romerox3/volra"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romerox3/volra/releases/download/v1.0.2/volra-1.0.2-darwin-amd64.tar.gz"
      sha256 "dbb5094a828552a3ef99c4e502aaeb829478925e7170913ac2eac5989df0fc54"

      define_method(:install) do
        bin.install "volra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romerox3/volra/releases/download/v1.0.2/volra-1.0.2-darwin-arm64.tar.gz"
      sha256 "15b4a113119244de31af90a5294d207b7c5a6c8a714f2e85f8f86e0c04a58e38"

      define_method(:install) do
        bin.install "volra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/romerox3/volra/releases/download/v1.0.2/volra-1.0.2-linux-amd64.tar.gz"
      sha256 "ec545517e50be5c1a432d546ea8f2d6029eeaad64900224b4b8cd4c8005e9781"
      define_method(:install) do
        bin.install "volra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/romerox3/volra/releases/download/v1.0.2/volra-1.0.2-linux-arm64.tar.gz"
      sha256 "a289a0e33f63c5da0f773e304bee42e2dc658383dd6967ba4399dcea215f7516"
      define_method(:install) do
        bin.install "volra"
      end
    end
  end

  test do
    system "#{bin}/volra", "--version"
  end
end
